# Generated by Django 4.2.4 on 2023-08-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={'managed': True},
        ),
    ]
